"use client"

import "./globals.css";
import { russo, roboto } from "./fonts";
import Aside_Sec from "./components/aside_sec/aside_sec";
import Hamburger from "./components/hamburger/hambuger";
import Banner from "./components/banner/banner";
import React, { useState, useEffect, useRef } from "react";
import styles from './page.module.css';


const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {const [open_menu, set_open_menu] = useState(false)
    const [selected_content, set_selected_content] = useState(0)
    const [doc_size, set_doc_size] = useState(1000)

    const filter_ref = useRef(null)

    useEffect(() => {
        const resize = () => {
            set_doc_size(document.documentElement.scrollHeight);
        };

        resize();
        window.addEventListener('resize', resize);

        return () => {
            window.removeEventListener('resize', resize);
        };
    }, []);

    useEffect(() => {
        if (filter_ref.current) {
            filter_ref.current.style.height = `${doc_size}px`;
        }
    }, [doc_size]);

    // Fonction d'ouverture du menu de navigation
    const handle_click = ()=>{
        set_open_menu(prev=>!prev)
    }

    // Fonction de gestion de la selection
    const handle_selection = (e) => {
        const value = parseInt(e.target.value, 10);
        set_selected_content(value);
        console.log(value)
    }
    
  return (
    <html lang="en">
        <body className={roboto.className}>
            
            <Aside_Sec selected_content={selected_content} open_menu={open_menu} />
            <main className={styles.main}>
                {React.Children.map(children, child => {
                    return React.cloneElement(child, { selected_content, set_selected_content });
                })}
                <Banner handle_selection={handle_selection} />
                <div ref={filter_ref} className={`${styles.filter} ${open_menu ? "visible": "unvisible"}`}>
                </div> 
            </main>
            <div className={styles.menu_div} onClick={()=>handle_click()}>
                <div className={styles.burger_div} style={!open_menu ? {borderRadius: "6px"}: {borderRadius: "50%"}}>
                <Hamburger open={open_menu} />
                </div>
                <h2>MENU</h2>
            </div>
        
        </body>
    </html>
  );
}
