import "./globals.css";

import { inter } from "./fonts";
import { russo } from "./fonts";


const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body className={russo.className}>
            {children}
        </body>
    </html>
  );
}
