"use client"

import "./globals.css";
import { russo, roboto } from "./fonts";
import Aside_Sec from "./components/aside_sec/aside_sec";
import Hamburger from "./components/hamburger/hambuger";
import Banner from "./components/banner/banner";
import React, { useState, useEffect, useRef } from "react";
import styles from './page.module.css';
import { motion } from "framer-motion";


const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const pageVariants = {
    initial: { opacity: 0 },
    in: { opacity: 1 },
    out: { opacity: 0 },
  };
  
  const pageTransition = {
    type: "tween",
    ease: "anticipate",
    duration: 0.5,
  };
  
  export default function RootLayout({ children }) {
    const [open_menu, set_open_menu] = useState(false);
    const [doc_size, set_doc_size] = useState(1000);
    const filter_ref = useRef(null);
  
    useEffect(() => {
      const resize = () => {
        set_doc_size(document.documentElement.scrollHeight);
      };
  
      resize();
      window.addEventListener('resize', resize);
      window.addEventListener('load', resize);
  
      return () => {
        window.removeEventListener('resize', resize);
        window.removeEventListener('load', resize);
      };
    }, []);
  
    useEffect(() => {
      if (filter_ref.current) {
        filter_ref.current.style.height = `${doc_size}px`;
      }
    }, [doc_size]);
  
    const handle_click = () => {
      set_open_menu(prev => !prev);
    };
  
    // Assumez ici que handle_selection et d'autres logiques sont définies
  
    return (
        <html lang="en">
          <body className={roboto.className}>
            <motion.div
                initial="initial"
                animate="in"
                exit="out"
                variants={pageVariants}
                transition={pageTransition}
            >
                <Aside_Sec close_menu={() => set_open_menu(false)} open_menu={open_menu} />
            </motion.div>
            <main className={styles.main}>
                <motion.div
                    initial="initial"
                    animate="in"
                    exit="out"
                    variants={pageVariants}
                    transition={pageTransition}
                >
                    {children}
                </motion.div>
              
              <Banner /* handle_selection={handle_selection} */ />
              <div ref={filter_ref} className={`${styles.filter} ${open_menu ? "visible" : "unvisible"}`}>
              </div> 
            </main>
            <div className={styles.menu_div} onClick={() => handle_click()}>
              <div className={styles.burger_div} style={!open_menu ? {borderRadius: "6px"} : {borderRadius: "50%"}}>
                <Hamburger open={open_menu} />
              </div>
              <h2>MENU</h2>
            </div>
          </body>
        </html>
    );
  }
